export const CATEGORIES = [
  "Tout",
  "Coran",
  "Hadith",
  "Fiqh",
  "Aqida",
  "Tafsir",
  "Sira / Biographies",
  "Langue Arabe",
  "Livres Enfants",
  "Études supérieures",
  "Moutoun",
];

export const CONDITIONS = ["Très bon", "Bon", "Correct"];

export const COUNTRIES = ["France", "Belgique"] as const;

export const BELGIUM_CITIES = [
  "Anvers",
  "Gand",
  "Charleroi",
  "Liège",
  "Bruxelles",
  "Schaerbeek",
  "Anderlecht",
  "Bruges",
  "Namur",
  "Louvain",
  "Mons",
  "Molenbeek-Saint-Jean",
  "Ixelles",
  "Alost",
  "La Louvière",
  "Uccle",
  "Hasselt",
  "Malines",
  "Tournai",
  "Courtrai",
  "Seraing",
  "Roulers",
  "Verviers",
  "Forest",
  "Etterbeek",
  "Mouscron",
  "Beveren",
  "Saint-Nicolas",
  "Genk",
  "Saint-Gilles",
  "Wavre",
  "Ottignies-Louvain-la-Neuve",
  "Braine-l'Alleud",
  "Waterloo",
  "Nivelles",
  "Soignies",
  "Arlon",
  "Bastogne",
  "Marche-en-Famenne",
  "Dinant",
  "Huy",
  "Spa",
  "Eupen",
  "Ostende",
  "Ypres",
  "Dixmude",
  "Furnes",
];

// Codes postaux pour villes courantes (FR & BE). Auto-remplissage à la sélection.
export const CITY_POSTAL_CODES: Record<string, string> = {
  // France — principales
  Paris: "75001",
  Marseille: "13001",
  Lyon: "69001",
  Toulouse: "31000",
  Nice: "06000",
  Nantes: "44000",
  Strasbourg: "67000",
  Montpellier: "34000",
  Bordeaux: "33000",
  Lille: "59000",
  Rennes: "35000",
  Reims: "51100",
  "Le Havre": "76600",
  "Saint-Étienne": "42000",
  Toulon: "83000",
  Grenoble: "38000",
  Dijon: "21000",
  Angers: "49000",
  Nîmes: "30000",
  Villeurbanne: "69100",
  "Le Mans": "72000",
  "Aix-en-Provence": "13100",
  "Clermont-Ferrand": "63000",
  Brest: "29200",
  Tours: "37000",
  Amiens: "80000",
  Limoges: "87000",
  Annecy: "74000",
  Perpignan: "66000",
  "Boulogne-Billancourt": "92100",
  Metz: "57000",
  Besançon: "25000",
  Orléans: "45000",
  Rouen: "76000",
  Mulhouse: "68100",
  Caen: "14000",
  Nancy: "54000",
  "Saint-Denis": "93200",
  Argenteuil: "95100",
  Roubaix: "59100",
  Tourcoing: "59200",
  Avignon: "84000",
  Versailles: "78000",
  Cannes: "06400",
  Antibes: "06600",
  Béziers: "34500",
  Pau: "64000",
  Calais: "62100",
  "La Rochelle": "17000",
  Bourges: "18000",
  Ajaccio: "20000",
  Bayonne: "64100",
  "Saint-Nazaire": "44600",
  Colmar: "68000",
  "Vitry-sur-Seine": "94400",
  Courbevoie: "92400",
  Créteil: "94000",
  Nanterre: "92000",
  Aubervilliers: "93300",
  "Asnières-sur-Seine": "92600",
  Poitiers: "86000",
  "Cherbourg-en-Cotentin": "50100",
  Beauvais: "60000",
  Cayenne: "97300",
  "Fort-de-France": "97200",
  "Saint-Paul": "97460",
  // Belgique
  Bruxelles: "1000",
  Anvers: "2000",
  Gand: "9000",
  Charleroi: "6000",
  Liège: "4000",
  Bruges: "8000",
  Namur: "5000",
  Louvain: "3000",
  Mons: "7000",
  Hasselt: "3500",
  Malines: "2800",
  Tournai: "7500",
  Courtrai: "8500",
  Ostende: "8400",
  Schaerbeek: "1030",
  Anderlecht: "1070",
  Ixelles: "1050",
  Uccle: "1180",
  Forest: "1190",
  Etterbeek: "1040",
  "Saint-Gilles": "1060",
  "Molenbeek-Saint-Jean": "1080",
  Waterloo: "1410",
  Wavre: "1300",
  Nivelles: "1400",
  Arlon: "6700",
  Dinant: "5500",
};
export const ALL_CITIES = [
  "Abbeville",
  "Ablon-sur-Seine",
  "Achicourt",
  "Achères",
  "Acigné",
  "Acoua",
  "Agde",
  "Agen",
  "Aiffres",
  "Aigues-Mortes",
  "Aimargues",
  "Aire-sur-l'Adour",
  "Aire-sur-la-Lys",
  "Aix-en-Provence",
  "Aix-les-Bains",
  "Aixe-sur-Vienne",
  "Aizenay",
  "Ajaccio",
  "Albert",
  "Albertville",
  "Albi",
  "Alençon",
  "Alfortville",
  "Algrange",
  "Allauch",
  "Allinges",
  "Allonnes",
  "Altkirch",
  "Alès",
  "Ambarès-et-Lagrave",
  "Ambazac",
  "Ambert",
  "Ambilly",
  "Amboise",
  "Ambérieu-en-Bugey",
  "Amiens",
  "Amilly",
  "Amnéville",
  "Ancenis-Saint-Géréon",
  "Andernos-les-Bains",
  "Andrésy",
  "Andrézieux-Bouthéon",
  "Angers",
  "Anglet",
  "Angoulême",
  "Aniche",
  "Annecy",
  "Annemasse",
  "Annezin",
  "Annonay",
  "Annœullin",
  "Anse",
  "Antibes",
  "Antony",
  "Anzin",
  "Apatou",
  "Apt",
  "Arcachon",
  "Arcueil",
  "Argelès-sur-Mer",
  "Argentan",
  "Argenteuil",
  "Arles",
  "Armentières",
  "Arnage",
  "Arnouville",
  "Arpajon",
  "Arpajon-sur-Cère",
  "Arques",
  "Arradon",
  "Arras",
  "Artigues-près-Bordeaux",
  "Arue",
  "Arès",
  "Asnières-sur-Seine",
  "Athis-Mons",
  "Aubagne",
  "Aubenas",
  "Aubergenville",
  "Aubervilliers",
  "Aubignan",
  "Aubigny-Les Clouzeaux",
  "Aubigny-sur-Nère",
  "Aubière",
  "Auby",
  "Aucamville",
  "Auch",
  "Auchel",
  "Audenge",
  "Audincourt",
  "Audruicq",
  "Audun-le-Tiche",
  "Aulnay-sous-Bois",
  "Aulnoy-lez-Valenciennes",
  "Aulnoye-Aymeries",
  "Auneau-Bleury-Saint-Symphorien",
  "Auray",
  "Aurec-sur-Loire",
  "Aureilhan",
  "Aurillac",
  "Auriol",
  "Aussillon",
  "Aussonne",
  "Auterive",
  "Autun",
  "Auvers-sur-Oise",
  "Auxerre",
  "Auxonne",
  "Avallon",
  "Avignon",
  "Avion",
  "Avon",
  "Avranches",
  "Avrillé",
  "Aytré",
  "Aÿ-Champagne",
  "Baden",
  "Bagneux",
  "Bagnolet",
  "Bagnols-sur-Cèze",
  "Bagnères-de-Bigorre",
  "Baie-Mahault",
  "Baillargues",
  "Bailleul",
  "Baillif",
  "Bailly-Romainvilliers",
  "Bain-de-Bretagne",
  "Baisieux",
  "Balaruc-les-Bains",
  "Ballan-Miré",
  "Ballancourt-sur-Essonne",
  "Balma",
  "Bandol",
  "Bandraboua",
  "Bandrele",
  "Bannalec",
  "Bar-le-Duc",
  "Barberaz",
  "Barentin",
  "Barlin",
  "Barr",
  "Basse-Goulaine",
  "Basse-Terre",
  "Bassens",
  "Bastia",
  "Baud",
  "Baugé-en-Anjou",
  "Baume-les-Dames",
  "Bauvin",
  "Bayeux",
  "Bayonne",
  "Beaucaire",
  "Beauchamp",
  "Beaucouzé",
  "Beaufort-en-Anjou",
  "Beaugency",
  "Beaumont",
  "Beaumont-sur-Oise",
  "Beaune",
  "Beaupréau-en-Mauges",
  "Beaurains",
  "Beaurepaire",
  "Beausoleil",
  "Beauvais",
  "Beauvoisin",
  "Beauzelle",
  "Behren-lès-Forbach",
  "Belfort",
  "Belin-Béliet",
  "Bellegarde",
  "Bellerive-sur-Allier",
  "Bellevigne-en-Layon",
  "Bellevigny",
  "Belleville-en-Beaujolais",
  "Belley",
  "Benfeld",
  "Berck",
  "Bergerac",
  "Bernay",
  "Berre-l'Étang",
  "Besançon",
  "Bessan",
  "Bessancourt",
  "Bethoncourt",
  "Betton",
  "Beuvrages",
  "Beuvry",
  "Beynes",
  "Beynost",
  "Bezannes",
  "Bezons",
  "Biarritz",
  "Bidart",
  "Biganos",
  "Biguglia",
  "Bihorel",
  "Billy-Berclau",
  "Billy-Montigny",
  "Billère",
  "Binic-Étables-sur-Mer",
  "Biot",
  "Biscarrosse",
  "Bischheim",
  "Bischwiller",
  "Blagnac",
  "Blain",
  "Blainville-sur-Orne",
  "Blanquefort",
  "Blanzy",
  "Blaye",
  "Blois",
  "Blotzheim",
  "Bléré",
  "Bobigny",
  "Bohain-en-Vermandois",
  "Bois-Colombes",
  "Bois-Guillaume",
  "Bois-d'Arcy",
  "Bois-le-Roi",
  "Boissy-Saint-Léger",
  "Bolbec",
  "Bollène",
  "Bompas",
  "Bon-Encontre",
  "Bonchamp-lès-Laval",
  "Bondoufle",
  "Bondues",
  "Bondy",
  "Bonneuil-sur-Marne",
  "Bonneville",
  "Bonnières-sur-Seine",
  "Bons-en-Chablais",
  "Bonsecours",
  "Bora-Bora",
  "Bordeaux",
  "Bordères-sur-l'Échez",
  "Borgo",
  "Bormes-les-Mimosas",
  "Bouaye",
  "Bouc-Bel-Air",
  "Boucau",
  "Bouchemaine",
  "Bouffémont",
  "Bougival",
  "Bouguenais",
  "Bouillante",
  "Bouillargues",
  "Boulay-Moselle",
  "Boulazac Isle Manoire",
  "Boulogne-Billancourt",
  "Boulogne-sur-Mer",
  "Bourail",
  "Bourbourg",
  "Bourg-Saint-Andéol",
  "Bourg-Saint-Maurice",
  "Bourg-de-Péage",
  "Bourg-en-Bresse",
  "Bourg-la-Reine",
  "Bourg-lès-Valence",
  "Bourges",
  "Bourgoin-Jallieu",
  "Boussy-Saint-Antoine",
  "Bouéni",
  "Boé",
  "Bras-Panon",
  "Brebières",
  "Brech",
  "Bressuire",
  "Brest",
  "Bretignolles-sur-Mer",
  "Breuillet",
  "Briançon",
  "Bricquebec-en-Cotentin",
  "Brie-Comte-Robert",
  "Briec",
  "Brignais",
  "Brignoles",
  "Brindas",
  "Brioude",
  "Brissac Loire Aubance",
  "Brive-la-Gaillarde",
  "Bron",
  "Brou-sur-Chantereine",
  "Bruay-la-Buissière",
  "Bruay-sur-l'Escaut",
  "Bruges",
  "Bruguières",
  "Brumath",
  "Brunoy",
  "Brunstatt-Didenheim",
  "Bruz",
  "Bry-sur-Marne",
  "Bréal-sous-Montfort",
  "Brétigny-sur-Orge",
  "Buc",
  "Bully-les-Mines",
  "Bures-sur-Yvette",
  "Bussy-Saint-Georges",
  "Buxerolles",
  "Bègles",
  "Bédarieux",
  "Bédarrides",
  "Bétheny",
  "Béthune",
  "Béziers",
  "Cabestany",
  "Cabriès",
  "Cachan",
  "Cadaujac",
  "Caen",
  "Cagnes-sur-Mer",
  "Cahors",
  "Calais",
  "Calonne-Ricouart",
  "Caluire-et-Cuire",
  "Calvi",
  "Calvisson",
  "Cambo-les-Bains",
  "Cambrai",
  "Cancale",
  "Canet-en-Roussillon",
  "Cannes",
  "Canohès",
  "Canteleu",
  "Canéjan",
  "Capbreton",
  "Capesterre-Belle-Eau",
  "Cappelle-la-Grande",
  "Carbon-Blanc",
  "Carbonne",
  "Carcassonne",
  "Carentan-les-Marais",
  "Carhaix-Plouguer",
  "Carmaux",
  "Carnoux-en-Provence",
  "Carpentras",
  "Carquefou",
  "Carqueiranne",
  "Carrières-sous-Poissy",
  "Carrières-sur-Seine",
  "Carros",
  "Carry-le-Rouet",
  "Carvin",
  "Cassis",
  "Castanet-Tolosan",
  "Castelginest",
  "Castelnau-d'Estrétefonds",
  "Castelnau-le-Lez",
  "Castelnaudary",
  "Castelsarrasin",
  "Castres",
  "Castries",
  "Caudan",
  "Caudebec-lès-Elbeuf",
  "Caudry",
  "Caumont-sur-Durance",
  "Caussade",
  "Cavaillon",
  "Cavalaire-sur-Mer",
  "Cayenne",
  "Cazouls-lès-Béziers",
  "Cenon",
  "Cergy",
  "Cernay",
  "Cesson",
  "Cesson-Sévigné",
  "Cessy",
  "Cestas",
  "Ceyrat",
  "Chabeuil",
  "Chagny",
  "Challans",
  "Challes-les-Eaux",
  "Chalon-sur-Saône",
  "Chalonnes-sur-Loire",
  "Chamalières",
  "Chambly",
  "Chambourcy",
  "Chambray-lès-Tours",
  "Chambéry",
  "Chamonix-Mont-Blanc",
  "Champagne-au-Mont-d'Or",
  "Champagne-sur-Oise",
  "Champagne-sur-Seine",
  "Champagnole",
  "Champigneulles",
  "Champigny-sur-Marne",
  "Champniers",
  "Champs-sur-Marne",
  "Changé",
  "Chanteloup-les-Vignes",
  "Chantepie",
  "Chantilly",
  "Chantonnay",
  "Chanverrie",
  "Chaponost",
  "Charbonnières-les-Bains",
  "Charenton-le-Pont",
  "Charleville-Mézières",
  "Charnay-lès-Mâcon",
  "Chartres",
  "Chartres-de-Bretagne",
  "Charvieu-Chavagneux",
  "Chasse-sur-Rhône",
  "Chassieu",
  "Chatou",
  "Chatuzange-le-Goubet",
  "Chaumes-en-Retz",
  "Chaumont",
  "Chauny",
  "Chauray",
  "Chauvigny",
  "Chavanoz",
  "Chaville",
  "Chazelles-sur-Lyon",
  "Chelles",
  "Chemillé-en-Anjou",
  "Chennevières-sur-Marne",
  "Chenôve",
  "Cherbourg-en-Cotentin",
  "Chessy",
  "Chevigny-Saint-Sauveur",
  "Chevilly-Larue",
  "Chevreuse",
  "Chiconi",
  "Chilly-Mazarin",
  "Chinon",
  "Chirongui",
  "Choisy-le-Roi",
  "Cholet",
  "Châlette-sur-Loing",
  "Châlons-en-Champagne",
  "Château-Arnoux-Saint-Auban",
  "Château-Gontier-sur-Mayenne",
  "Château-Thierry",
  "Châteaubourg",
  "Châteaubriant",
  "Châteaudun",
  "Châteaugiron",
  "Châteaulin",
  "Châteauneuf-les-Martigues",
  "Châteauneuf-sur-Loire",
  "Châteaurenard",
  "Châteauroux",
  "Châtel-Guyon",
  "Châtelaillon-Plage",
  "Châtellerault",
  "Châtenay-Malabry",
  "Châtenoy-le-Royal",
  "Châtillon",
  "Châtillon-sur-Chalaronne",
  "Châtillon-sur-Seine",
  "Chécy",
  "Ciboure",
  "Cilaos",
  "Claix",
  "Clamart",
  "Clapiers",
  "Claye-Souilly",
  "Clermont",
  "Clermont-Ferrand",
  "Clermont-l'Hérault",
  "Clichy",
  "Clichy-sous-Bois",
  "Clisson",
  "Cloyes-les-Trois-Rivières",
  "Cluses",
  "Cognac",
  "Cognin",
  "Cogolin",
  "Colmar",
  "Colombelles",
  "Colombes",
  "Colomiers",
  "Combourg",
  "Combs-la-Ville",
  "Comines",
  "Commentry",
  "Commercy",
  "Compiègne",
  "Concarneau",
  "Condat-sur-Vienne",
  "Condom",
  "Condé-en-Normandie",
  "Condé-sur-l'Escaut",
  "Conflans-Sainte-Honorine",
  "Contes",
  "Corbas",
  "Corbeil-Essonnes",
  "Corbie",
  "Cormeilles-en-Parisis",
  "Cormelles-le-Royal",
  "Cormontreuil",
  "Cornebarrieu",
  "Corte",
  "Cosne-Cours-sur-Loire",
  "Coublevie",
  "Coubron",
  "Coudekerque-Branche",
  "Coulaines",
  "Coulogne",
  "Coulommiers",
  "Coulounieix-Chamiers",
  "Courbevoie",
  "Courcelles-lès-Lens",
  "Courdimanche",
  "Cournon-d'Auvergne",
  "Cournonterral",
  "Courrières",
  "Coursan",
  "Courthézon",
  "Courtry",
  "Coutances",
  "Coutras",
  "Couzeix",
  "Couëron",
  "Cranves-Sales",
  "Craponne",
  "Creil",
  "Crest",
  "Creutzwald",
  "Croissy-sur-Seine",
  "Croix",
  "Crolles",
  "Crosne",
  "Crozon",
  "Cruseilles",
  "Crégy-lès-Meaux",
  "Crépy-en-Valois",
  "Créteil",
  "Cucq",
  "Cuers",
  "Cugand-la-Bernardière",
  "Cuges-les-Pins",
  "Cugnaux",
  "Cuincy",
  "Cusset",
  "Cébazat",
  "Céret",
  "Dainville",
  "Dammarie-les-Lys",
  "Dammartin-en-Goële",
  "Dardilly",
  "Darnétal",
  "Dax",
  "Decazeville",
  "Dechy",
  "Delle",
  "Dembeni",
  "Denain",
  "Deuil-la-Barre",
  "Dieppe",
  "Digne-les-Bains",
  "Digoin",
  "Dijon",
  "Dinan",
  "Dinard",
  "Divatte-sur-Loire",
  "Dives-sur-Mer",
  "Divion",
  "Divonne-les-Bains",
  "Dol-de-Bretagne",
  "Dole",
  "Dombasle-sur-Meurthe",
  "Domont",
  "Dompierre-sur-Mer",
  "Domène",
  "Domérat",
  "Donges",
  "Donzère",
  "Douai",
  "Douarnenez",
  "Douchy-les-Mines",
  "Doullens",
  "Dourdan",
  "Dourges",
  "Douvaine",
  "Douvres-la-Délivrande",
  "Douvrin",
  "Doué-en-Anjou",
  "Draguignan",
  "Drancy",
  "Drap",
  "Draveil",
  "Dreux",
  "Drusenheim",
  "Ducos",
  "Dugny",
  "Dumbéa",
  "Dunkerque",
  "Dzaoudzi",
  "Décines-Charpieu",
  "Déols",
  "Déville-lès-Rouen",
  "Eaubonne",
  "Eaunes",
  "Eckbolsheim",
  "Elbeuf",
  "Elne",
  "Elven",
  "Embrun",
  "Enghien-les-Bains",
  "Ensisheim",
  "Ensuès-la-Redonne",
  "Entraigues-sur-la-Sorgue",
  "Entre-Deux",
  "Entrelacs",
  "Epagny Metz-Tessy",
  "Erdre-en-Anjou",
  "Ergué-Gabéric",
  "Ermont",
  "Ernée",
  "Erquinghem-Lys",
  "Erstein",
  "Esbly",
  "Escalquens",
  "Escaudain",
  "Eschau",
  "Essarts-en-Bocage",
  "Essey-lès-Nancy",
  "Estaires",
  "Esvres",
  "Eu",
  "Eybens",
  "Eyguières",
  "Eysines",
  "Faaa",
  "Fabrègues",
  "Faches-Thumesnil",
  "Falaise",
  "Fameck",
  "Farébersviller",
  "Faulquemont",
  "Faverges-Seythenex",
  "Fayence",
  "Fegersheim",
  "Feignies",
  "Fenain",
  "Fenouillet",
  "Ferney-Voltaire",
  "Ferrière-la-Grande",
  "Feurs",
  "Feytiat",
  "Feyzin",
  "Figeac",
  "Fillière",
  "Firminy",
  "Fismes",
  "Flers",
  "Flers-en-Escrebieux",
  "Fleurance",
  "Fleury-Mérogis",
  "Fleury-les-Aubrais",
  "Fleury-sur-Orne",
  "Flines-lez-Raches",
  "Floirac",
  "Florange",
  "Florensac",
  "Foix",
  "Fondettes",
  "Fonsorbes",
  "Fontaine",
  "Fontaine-lès-Dijon",
  "Fontainebleau",
  "Fontaines-sur-Saône",
  "Fontenay-Trésigny",
  "Fontenay-aux-Roses",
  "Fontenay-le-Comte",
  "Fontenay-le-Fleury",
  "Fontenay-sous-Bois",
  "Fontenilles",
  "Forbach",
  "Forcalquier",
  "Fort-de-France",
  "Fos-sur-Mer",
  "Fosses",
  "Fouesnant",
  "Fougères",
  "Foulayronnes",
  "Fouquières-lès-Lens",
  "Fourmies",
  "Francheville",
  "Franconville",
  "Franqueville-Saint-Pierre",
  "Fresnes",
  "Fresnes-sur-Escaut",
  "Freyming-Merlebach",
  "Frontignan",
  "Fronton",
  "Frouard",
  "Frouzins",
  "Fréjus",
  "Furiani",
  "Fuveau",
  "Fécamp",
  "Gagny",
  "Gaillac",
  "Gaillard",
  "Gaillon",
  "Gambsheim",
  "Gan",
  "Gannat",
  "Gap",
  "Garches",
  "Gardanne",
  "Gargenville",
  "Garges-lès-Gonesse",
  "Garons",
  "Garéoult",
  "Gauchy",
  "Geispolsheim",
  "Genas",
  "Genay",
  "Genlis",
  "Gennes-Val-de-Loire",
  "Gennevilliers",
  "Gentilly",
  "Gerzat",
  "Gex",
  "Giberville",
  "Gien",
  "Gif-sur-Yvette",
  "Gigean",
  "Gignac",
  "Gignac-la-Nerthe",
  "Gisors",
  "Givet",
  "Givors",
  "Gières",
  "Gleizé",
  "Golbey",
  "Gond-Pontouvre",
  "Gonesse",
  "Gonfreville-l'Orcher",
  "Gorges",
  "Gouesnou",
  "Gourbeyre",
  "Gournay-en-Bray",
  "Gournay-sur-Marne",
  "Goussainville",
  "Gouvieux",
  "Goyave",
  "Grabels",
  "Gradignan",
  "Grand-Champ",
  "Grand-Charmont",
  "Grand-Couronne",
  "Grand-Santi",
  "Grandchamp-des-Fontaines",
  "Grande-Synthe",
  "Grans",
  "Granville",
  "Grasse",
  "Graulhet",
  "Gravelines",
  "Gray",
  "Grenade",
  "Grenay",
  "Grenoble",
  "Gretz-Armainvilliers",
  "Grigny",
  "Grigny-sur-Rhône",
  "Gros-Morne",
  "Groslay",
  "Gruissan",
  "Grézieu-la-Varenne",
  "Guebwiller",
  "Guer",
  "Gueugnon",
  "Guichen",
  "Guidel",
  "Guilers",
  "Guilherand-Granges",
  "Guingamp",
  "Guipavas",
  "Guipry-Messac",
  "Gujan-Mestras",
  "Guyancourt",
  "Guémené-Penfao",
  "Guénange",
  "Guérande",
  "Guéret",
  "Guînes",
  "Gémenos",
  "Gérardmer",
  "Gévezé",
  "Habsheim",
  "Hagondange",
  "Haguenau",
  "Haillicourt",
  "Halluin",
  "Harfleur",
  "Harnes",
  "Hasparren",
  "Haubourdin",
  "Haute-Goulaine",
  "Hautmont",
  "Hauts de Bienne",
  "Hayange",
  "Hazebrouck",
  "Heillecourt",
  "Hem",
  "Hendaye",
  "Hennebont",
  "Herbignac",
  "Herblay-sur-Seine",
  "Hersin-Coupigny",
  "Hettange-Grande",
  "Hirson",
  "Hitiaa O Te Ra",
  "Hombourg-Haut",
  "Homécourt",
  "Honfleur",
  "Horbourg-Wihr",
  "Houdain",
  "Houilles",
  "Houplines",
  "Huahine",
  "Huningue",
  "Hyères",
  "Hénin-Beaumont",
  "Héric",
  "Héricourt",
  "Hérouville-Saint-Clair",
  "Hœnheim",
  "Idron",
  "Ifs",
  "Igny",
  "Ille-sur-Têt",
  "Illkirch-Graffenstaden",
  "Illzach",
  "Ingré",
  "Inzinzac-Lochrist",
  "Irigny",
  "Isbergues",
  "Isle",
  "Issoire",
  "Issoudun",
  "Issy-les-Moulineaux",
  "Istres",
  "Itteville",
  "Ivry-sur-Seine",
  "Izon",
  "Jacou",
  "Janzé",
  "Jarny",
  "Jarville-la-Malgrange",
  "Jassans-Riottier",
  "Jaunay-Marigny",
  "Jeumont",
  "Joigny",
  "Joinville-le-Pont",
  "Jonage",
  "Jonquières",
  "Jouars-Pontchartrain",
  "Jouy-en-Josas",
  "Jouy-le-Moutier",
  "Joué-lès-Tours",
  "Jurançon",
  "Juvignac",
  "Juvisy-sur-Orge",
  "Jœuf",
  "Kani-Kéli",
  "Kembs",
  "Kervignac",
  "Kingersheim",
  "Koné",
  "Koungou",
  "Kourou",
  "L'Aigle",
  "L'Arbresle",
  "L'Haÿ-les-Roses",
  "L'Hôpital",
  "L'Isle-Adam",
  "L'Isle-Jourdain",
  "L'Isle-d'Abeau",
  "L'Isle-d'Espagnac",
  "L'Isle-sur-la-Sorgue",
  "L'Union",
  "L'Étang-Salé",
  "L'Étang-la-Ville",
  "L'Île-Saint-Denis",
  "La Balme-de-Sillingy",
  "La Bassée",
  "La Baule-Escoublac",
  "La Bouilladisse",
  "La Cadière-d'Azur",
  "La Celle-Saint-Cloud",
  "La Chapelle-Saint-Luc",
  "La Chapelle-Saint-Mesmin",
  "La Chapelle-d'Armentières",
  "La Chapelle-sur-Erdre",
  "La Chevrolière",
  "La Ciotat",
  "La Colle-sur-Loup",
  "La Courneuve",
  "La Couronne",
  "La Crau",
  "La Crèche",
  "La Fare-les-Oliviers",
  "La Farlède",
  "La Ferrière",
  "La Ferté Macé",
  "La Ferté-Bernard",
  "La Ferté-Saint-Aubin",
  "La Ferté-sous-Jouarre",
  "La Flèche",
  "La Garde",
  "La Garenne-Colombes",
  "La Garnache",
  "La Gaude",
  "La Gorgue",
  "La Grande-Motte",
  "La Hague",
  "La Londe-les-Maures",
  "La Madeleine",
  "La Montagne",
  "La Motte-Servolex",
  "La Mulatière",
  "La Mézière",
  "La Penne-sur-Huveaune",
  "La Plaine-des-Palmistes",
  "La Possession",
  "La Queue-en-Brie",
  "La Ravoire",
  "La Ricamarie",
  "La Riche",
  "La Roche-sur-Foron",
  "La Roche-sur-Yon",
  "La Rochelle",
  "La Roque-d'Anthéron",
  "La Roquette-sur-Siagne",
  "La Salvetat-Saint-Gilles",
  "La Seyne-sur-Mer",
  "La Talaudière",
  "La Teste-de-Buch",
  "La Tour-du-Pin",
  "La Trinité",
  "La Tronche",
  "La Valette-du-Var",
  "La Verpillière",
  "La Verrière",
  "La Ville-aux-Dames",
  "La Ville-du-Bois",
  "La Wantzenau",
  "Labarthe-sur-Lèze",
  "Labenne",
  "Labruguière",
  "Lacanau",
  "Lacroix-Saint-Ouen",
  "Lagnieu",
  "Lagny-sur-Marne",
  "Lagord",
  "Laillé",
  "Lallaing",
  "Lamballe-Armor",
  "Lambersart",
  "Lambesc",
  "Lamentin",
  "Lamorlaye",
  "Landerneau",
  "Landivisiau",
  "Lanester",
  "Laneuveville-devant-Nancy",
  "Langon",
  "Langres",
  "Langueux",
  "Languidic",
  "Lannemezan",
  "Lannilis",
  "Lannion",
  "Lanton",
  "Lançon-Provence",
  "Laon",
  "Lardy",
  "Larmor-Plage",
  "Lattes",
  "Laudun-l'Ardoise",
  "Launaguet",
  "Laval",
  "Lavaur",
  "Lavelanet",
  "Laventie",
  "Laxou",
  "Le Barcarès",
  "Le Barp",
  "Le Beausset",
  "Le Blanc",
  "Le Blanc-Mesnil",
  "Le Boulou",
  "Le Bourget",
  "Le Bourget-du-Lac",
  "Le Bouscat",
  "Le Cannet",
  "Le Cannet-des-Maures",
  "Le Castellet",
  "Le Cateau-Cambrésis",
  "Le Cendre",
  "Le Chambon-Feugerolles",
  "Le Chesnay-Rocquencourt",
  "Le Controis-en-Sologne",
  "Le Coteau",
  "Le Creusot",
  "Le Crès",
  "Le Diamant",
  "Le François",
  "Le Gosier",
  "Le Grand-Quevilly",
  "Le Grau-du-Roi",
  "Le Haillan",
  "Le Havre",
  "Le Kremlin-Bicêtre",
  "Le Lamentin",
  "Le Lavandou",
  "Le Lion-d'Angers",
  "Le Loroux-Bottereau",
  "Le Lorrain",
  "Le Luc",
  "Le Malesherbois",
  "Le Mans",
  "Le Marin",
  "Le Mené",
  "Le Mesnil-Esnard",
  "Le Mesnil-Saint-Denis",
  "Le Mesnil-le-Roi",
  "Le Mont-Dore",
  "Le Moule",
  "Le Muy",
  "Le Mée-sur-Seine",
  "Le Palais-sur-Vienne",
  "Le Passage",
  "Le Pecq",
  "Le Pellerin",
  "Le Perray-en-Yvelines",
  "Le Perreux-sur-Marne",
  "Le Petit-Quevilly",
  "Le Pian-Médoc",
  "Le Plessis-Bouchard",
  "Le Plessis-Robinson",
  "Le Plessis-Trévise",
  "Le Poinçonnet",
  "Le Poiré-sur-Vie",
  "Le Pont-de-Claix",
  "Le Pontet",
  "Le Port",
  "Le Port-Marly",
  "Le Portel",
  "Le Pradet",
  "Le Pré-Saint-Gervais",
  "Le Puy-Sainte-Réparade",
  "Le Puy-en-Velay",
  "Le Péage-de-Roussillon",
  "Le Raincy",
  "Le Relecq-Kerhuon",
  "Le Rheu",
  "Le Robert",
  "Le Rove",
  "Le Soler",
  "Le Taillan-Médoc",
  "Le Tampon",
  "Le Teich",
  "Le Teil",
  "Le Thor",
  "Le Val d'Hazey",
  "Le Vauclin",
  "Le Vésinet",
  "Leers",
  "Leforest",
  "Lempdes",
  "Lens",
  "Lentilly",
  "Les Abrets en Dauphiné",
  "Les Abymes",
  "Les Achards",
  "Les Andelys",
  "Les Angles",
  "Les Arcs",
  "Les Avenières Veyrins-Thuellin",
  "Les Avirons",
  "Les Clayes-sous-Bois",
  "Les Essarts-le-Roi",
  "Les Hauts-d'Anjou",
  "Les Herbiers",
  "Les Lilas",
  "Les Mureaux",
  "Les Pavillons-sous-Bois",
  "Les Pennes-Mirabeau",
  "Les Ponts-de-Cé",
  "Les Sables-d'Olonne",
  "Les Sorinières",
  "Les Trois-Bassins",
  "Les Trois-Îlets",
  "Les Ulis",
  "Lescar",
  "Lesneven",
  "Lesparre-Médoc",
  "Lesquin",
  "Lestrem",
  "Levallois-Perret",
  "Levens",
  "Lezoux",
  "Liancourt",
  "Libercourt",
  "Libourne",
  "Lieusaint",
  "Liffré",
  "Lifou",
  "Ligné",
  "Lille",
  "Lillebonne",
  "Lillers",
  "Limay",
  "Limeil-Brévannes",
  "Limoges",
  "Limours",
  "Limoux",
  "Linas",
  "Lingolsheim",
  "Linselles",
  "Lisieux",
  "Lisses",
  "Livarot-Pays-d'Auge",
  "Liverdun",
  "Livron-sur-Drôme",
  "Livry-Gargan",
  "Liévin",
  "Loches",
  "Locmaria-Plouzané",
  "Lodève",
  "Lognes",
  "Loire-Authion",
  "Loireauxence",
  "Loison-sous-Lens",
  "Longjumeau",
  "Longpont-sur-Orge",
  "Longueau",
  "Longuenesse",
  "Longuenée-en-Anjou",
  "Longuyon",
  "Longué-Jumelles",
  "Longvic",
  "Longwy",
  "Lons",
  "Lons-le-Saunier",
  "Loon-Plage",
  "Loos",
  "Loos-en-Gohelle",
  "Lorgues",
  "Lorient",
  "Loriol-sur-Drôme",
  "Lormont",
  "Loudun",
  "Loudéac",
  "Louhans-Châteaurenaud",
  "Lourdes",
  "Louveciennes",
  "Louviers",
  "Louvres",
  "Louvroil",
  "Luc-la-Primaube",
  "Lucciana",
  "Lucé",
  "Ludon-Médoc",
  "Ludres",
  "Luisant",
  "Lunel",
  "Lunéville",
  "Lure",
  "Lutterbach",
  "Luxeuil-les-Bains",
  "Luynes",
  "Luzarches",
  "Luçon",
  "Lyon",
  "Lys-Haut-Layon",
  "Lys-lez-Lannoy",
  "Lège-Cap-Ferret",
  "Lèves",
  "Léguevin",
  "Léognan",
  "Lésigny",
  "Lézignan-Corbières",
  "M'Tsangamouji",
  "Mably",
  "Machecoul-Saint-Même",
  "Macouria",
  "Maen Roch",
  "Magnanville",
  "Magny-en-Vexin",
  "Magny-le-Hongre",
  "Magny-les-Hameaux",
  "Mahina",
  "Mainvilliers",
  "Maisons-Alfort",
  "Maisons-Laffitte",
  "Maizières-lès-Metz",
  "Malakoff",
  "Malaunay",
  "Malemort",
  "Mallemort",
  "Malzéville",
  "Mamoudzou",
  "Mana",
  "Mandelieu-la-Napoule",
  "Manduel",
  "Manosque",
  "Mantes-la-Jolie",
  "Mantes-la-Ville",
  "Marange-Silvange",
  "Marcheprime",
  "Marck",
  "Marcoussis",
  "Marcq-en-Barœul",
  "Marennes-Hiers-Brouage",
  "Margny-lès-Compiègne",
  "Marguerittes",
  "Marignane",
  "Marignier",
  "Maripasoula",
  "Marles-les-Mines",
  "Marly",
  "Marly-la-Ville",
  "Marly-le-Roi",
  "Marmande",
  "Marnaz",
  "Marolles-en-Hurepoix",
  "Maromme",
  "Marquette-lez-Lille",
  "Marquise",
  "Marsannay-la-Côte",
  "Marseillan",
  "Marseille",
  "Marsillargues",
  "Martignas-sur-Jalle",
  "Martigues",
  "Maré",
  "Massy",
  "Matoury",
  "Maubeuge",
  "Mauges-sur-Loire",
  "Mauguio",
  "Maule",
  "Mauléon",
  "Maurepas",
  "Maxéville",
  "Mayenne",
  "Mazamet",
  "Mazan",
  "Mazingarbe",
  "Mazé-Milon",
  "Meaux",
  "Mehun-sur-Yèvre",
  "Melesse",
  "Melle",
  "Melun",
  "Mende",
  "Mennecy",
  "Menton",
  "Menucourt",
  "Mer",
  "Merville",
  "Mesnils-sur-Iton",
  "Metz",
  "Meudon",
  "Meulan-en-Yvelines",
  "Meung-sur-Loire",
  "Meximieux",
  "Meylan",
  "Meyreuil",
  "Meyzieu",
  "Migennes",
  "Mignaloux-Beauvoir",
  "Migné-Auxances",
  "Milhaud",
  "Millau",
  "Mimizan",
  "Mions",
  "Mios",
  "Miramas",
  "Miribel",
  "Missillac",
  "Mitry-Mory",
  "Moirans",
  "Moissac",
  "Moissy-Cramayel",
  "Molsheim",
  "Moncoutant-sur-Sèvre",
  "Mondelange",
  "Mondeville",
  "Mondonville",
  "Monistrol-sur-Loire",
  "Mons-en-Barœul",
  "Mont-Saint-Aignan",
  "Mont-Saint-Martin",
  "Mont-de-Marsan",
  "Montaigu-Vendée",
  "Montargis",
  "Montataire",
  "Montauban",
  "Montauban-de-Bretagne",
  "Montauroux",
  "Montbonnot-Saint-Martin",
  "Montbrison",
  "Montbéliard",
  "Montceau-les-Mines",
  "Montdidier",
  "Montech",
  "Montereau-Fault-Yonne",
  "Montesson",
  "Monteux",
  "Montfermeil",
  "Montfort-sur-Meu",
  "Montgeron",
  "Montigny-en-Gohelle",
  "Montigny-le-Bretonneux",
  "Montigny-lès-Cormeilles",
  "Montigny-lès-Metz",
  "Montivilliers",
  "Montlhéry",
  "Montlouis-sur-Loire",
  "Montluel",
  "Montluçon",
  "Montmagny",
  "Montmorency",
  "Montmorillon",
  "Montoir-de-Bretagne",
  "Montpellier",
  "Montpon-Ménestérol",
  "Montreuil",
  "Montreuil-Juigné",
  "Montrevault-sur-Èvre",
  "Montrond-les-Bains",
  "Montrouge",
  "Monts",
  "Montval-sur-Loir",
  "Montélimar",
  "Montévrain",
  "Moorea-Maiao",
  "Morangis",
  "Morcenx-la-Nouvelle",
  "Mordelles",
  "Moret-Loing-et-Orvanne",
  "Morières-lès-Avignon",
  "Morlaix",
  "Mormant",
  "Mornant",
  "Morne-à-l'Eau",
  "Morsang-sur-Orge",
  "Mortagne-sur-Sèvre",
  "Morteau",
  "Mouans-Sartoux",
  "Mougins",
  "Mouguerre",
  "Mouilleron-le-Captif",
  "Moulins",
  "Moulins-lès-Metz",
  "Mourenx",
  "Mouroux",
  "Mouvaux",
  "Mouy",
  "Moyeuvre-Grande",
  "Moëlan-sur-Mer",
  "Mtsamboro",
  "Mulhouse",
  "Mulsanne",
  "Mundolsheim",
  "Muret",
  "Mutzig",
  "Muzillac",
  "Mâcon",
  "Mèze",
  "Méricourt",
  "Mériel",
  "Mérignac",
  "Méru",
  "Méry-sur-Oise",
  "Mézidon Vallée d'Auge",
  "Mûrs-Erigné",
  "Naintré",
  "Nancy",
  "Nandy",
  "Nangis",
  "Nans-les-Pins",
  "Nanterre",
  "Nantes",
  "Nanteuil-lès-Meaux",
  "Narbonne",
  "Nemours",
  "Neufchâteau",
  "Neuilly-Plaisance",
  "Neuilly-sur-Marne",
  "Neuilly-sur-Seine",
  "Neuves-Maisons",
  "Neuville-de-Poitou",
  "Neuville-en-Ferrain",
  "Neuville-sur-Saône",
  "Nevers",
  "Nice",
  "Nieppe",
  "Nieul-sur-Mer",
  "Niort",
  "Nogent-le-Rotrou",
  "Nogent-sur-Marne",
  "Nogent-sur-Oise",
  "Nogent-sur-Seine",
  "Noisiel",
  "Noisy-le-Grand",
  "Noisy-le-Roi",
  "Noisy-le-Sec",
  "Nort-sur-Erdre",
  "Notre-Dame-de-Bondeville",
  "Nouméa",
  "Nouzonville",
  "Noves",
  "Noyal-Châtillon-sur-Seiche",
  "Noyal-sur-Vilaine",
  "Noyant-Villages",
  "Noyelles-Godault",
  "Noyelles-sous-Lens",
  "Noyon",
  "Nueil-les-Aubiers",
  "Nuits-Saint-Georges",
  "Nyons",
  "Nègrepelisse",
  "Nérac",
  "Nîmes",
  "Nœux-les-Mines",
  "Oberhausbergen",
  "Obernai",
  "Octeville-sur-Mer",
  "Oignies",
  "Oissel-sur-Seine",
  "Olivet",
  "Ollainville",
  "Ollioules",
  "Oloron-Sainte-Marie",
  "Ombrée d'Anjou",
  "Ondres",
  "Onet-le-Château",
  "Onnaing",
  "Oraison",
  "Orange",
  "Orchies",
  "Orgeval",
  "Orgères",
  "Orly",
  "Orléans",
  "Ormesson-sur-Marne",
  "Ornex",
  "Orsay",
  "Orthez",
  "Orvault",
  "Orée d'Anjou",
  "Osny",
  "Ostricourt",
  "Ostwald",
  "Othis",
  "Ouangani",
  "Ouistreham",
  "Oullins-Pierre-Bénite",
  "Outreau",
  "Oye-Plage",
  "Oyonnax",
  "Ozoir-la-Ferrière",
  "Pacy-sur-Eure",
  "Pacé",
  "Paea",
  "Paimpol",
  "Palaiseau",
  "Palavas-les-Flots",
  "Pamandzi",
  "Pamiers",
  "Panazol",
  "Pantin",
  "Papaichton",
  "Papara",
  "Papeete",
  "Paray-Vieille-Poste",
  "Paray-le-Monial",
  "Parempuyre",
  "Parentis-en-Born",
  "Parigné-l'Évêque",
  "Paris",
  "Parmain",
  "Parthenay",
  "Passy",
  "Pau",
  "Pauillac",
  "Pavilly",
  "Païta",
  "Pecquencourt",
  "Penmarch",
  "Pernes-les-Fontaines",
  "Perpignan",
  "Perros-Guirec",
  "Persan",
  "Pertuis",
  "Pessac",
  "Petit-Bourg",
  "Petit-Canal",
  "Petit-Caux",
  "Petit-Couronne",
  "Petite-Forêt",
  "Petite-Rosselle",
  "Petite-Île",
  "Peymeinade",
  "Peypin",
  "Peyrolles-en-Provence",
  "Pfastatt",
  "Pia",
  "Pibrac",
  "Pierrefeu-du-Var",
  "Pierrelatte",
  "Pierrelaye",
  "Pignan",
  "Piolenc",
  "Pirae",
  "Pithiviers",
  "Plabennec",
  "Plaisance-du-Touch",
  "Plaisir",
  "Plan-de-Cuques",
  "Plescop",
  "Plessé",
  "Pleurtuit",
  "Ploemeur",
  "Ploeren",
  "Plonéour-Lanvern",
  "Plouay",
  "Ploudalmézeau",
  "Ploufragan",
  "Plougastel-Daoulas",
  "Plouguerneau",
  "Plouhinec",
  "Plouigneau",
  "Ploumagoar",
  "Plouzané",
  "Ploërmel",
  "Pluneret",
  "Pluvigner",
  "Plédran",
  "Plérin",
  "Pointe-Noire",
  "Pointe-à-Pitre",
  "Poissy",
  "Poisy",
  "Poitiers",
  "Pollestres",
  "Pont-Audemer",
  "Pont-Saint-Esprit",
  "Pont-Saint-Martin",
  "Pont-Sainte-Marie",
  "Pont-Sainte-Maxence",
  "Pont-de-Chéruy",
  "Pont-du-Château",
  "Pont-l'Abbé",
  "Pont-l'Évêque",
  "Pont-Évêque",
  "Pont-à-Mousson",
  "Pontarlier",
  "Pontault-Combault",
  "Pontcharra",
  "Pontchâteau",
  "Pontivy",
  "Pontoise",
  "Pordic",
  "Pornic",
  "Pornichet",
  "Port-Jérôme-sur-Seine",
  "Port-Louis",
  "Port-Saint-Louis-du-Rhône",
  "Port-de-Bouc",
  "Port-la-Nouvelle",
  "Portes-lès-Valence",
  "Portet-sur-Garonne",
  "Porto-Vecchio",
  "Pourrières",
  "Poussan",
  "Pouzauges",
  "Prades",
  "Prades-le-Lez",
  "Privas",
  "Provins",
  "Prévessin-Moëns",
  "Publier",
  "Puget-sur-Argens",
  "Puilboreau",
  "Pulnoy",
  "Punaauia",
  "Puteaux",
  "Pégomas",
  "Pélissanne",
  "Pérenchies",
  "Périgny",
  "Périgueux",
  "Pérols",
  "Péronnas",
  "Péronne",
  "Pézenas",
  "Quesnoy-sur-Deûle",
  "Questembert",
  "Quetigny",
  "Quimper",
  "Quimperlé",
  "Quincy-Voisins",
  "Quincy-sous-Sénart",
  "Quint-Fonsegrives",
  "Quiévrechain",
  "Quéven",
  "Rabastens",
  "Raismes",
  "Rambervillers",
  "Rambouillet",
  "Ramonville-Saint-Agne",
  "Raon-l'Étape",
  "Redon",
  "Reichshoffen",
  "Reignier-Ésery",
  "Reims",
  "Remire-Montjoly",
  "Remiremont",
  "Rennes",
  "Rethel",
  "Revel",
  "Revin",
  "Reyrieux",
  "Rezé",
  "Riantec",
  "Riedisheim",
  "Rillieux-la-Pape",
  "Riom",
  "Riorges",
  "Ris-Orangis",
  "Rive-de-Gier",
  "Rives",
  "Rives-du-Loir-en-Anjou",
  "Rivesaltes",
  "Rivière-Pilote",
  "Rivière-Salée",
  "Rixheim",
  "Roanne",
  "Rocbaron",
  "Roche-la-Molière",
  "Rochefort",
  "Rochefort-du-Gard",
  "Rodez",
  "Rognac",
  "Roissy-en-Brie",
  "Romagnat",
  "Romainville",
  "Romans-sur-Isère",
  "Rombas",
  "Romilly-sur-Seine",
  "Romorantin-Lanthenay",
  "Ronchin",
  "Roncq",
  "Roost-Warendin",
  "Roquebrune-Cap-Martin",
  "Roquebrune-sur-Argens",
  "Roquefort-la-Bédoule",
  "Roquefort-les-Pins",
  "Roquemaure",
  "Roques",
  "Roquevaire",
  "Rosheim",
  "Rosny-sous-Bois",
  "Rosny-sur-Seine",
  "Rosporden",
  "Roubaix",
  "Rouen",
  "Rousset",
  "Roussillon",
  "Rouvroy",
  "Royan",
  "Roye",
  "Rueil-Malmaison",
  "Ruelle-sur-Touvre",
  "Rumilly",
  "Rungis",
  "Sablé-sur-Sarthe",
  "Sada",
  "Sainghin-en-Weppes",
  "Sains-en-Gohelle",
  "Saint-Affrique",
  "Saint-Alban",
  "Saint-Alban-Leysse",
  "Saint-Amand-Montrond",
  "Saint-Amand-les-Eaux",
  "Saint-André",
  "Saint-André-de-Cubzac",
  "Saint-André-de-Sangonis",
  "Saint-André-de-la-Roche",
  "Saint-André-des-Eaux",
  "Saint-André-les-Vergers",
  "Saint-André-lez-Lille",
  "Saint-Apollinaire",
  "Saint-Arnoult-en-Yvelines",
  "Saint-Astier",
  "Saint-Aubin-de-Médoc",
  "Saint-Aubin-lès-Elbeuf",
  "Saint-Avertin",
  "Saint-Avold",
  "Saint-Avé",
  "Saint-Barthélemy",
  "Saint-Barthélemy-d'Anjou",
  "Saint-Benoît",
  "Saint-Berthevin",
  "Saint-Bonnet-de-Mure",
  "Saint-Brevin-les-Pins",
  "Saint-Brice-sous-Forêt",
  "Saint-Brieuc",
  "Saint-Cannat",
  "Saint-Chamas",
  "Saint-Chamond",
  "Saint-Christol-lez-Alès",
  "Saint-Chéron",
  "Saint-Claude",
  "Saint-Cloud",
  "Saint-Clément-de-Rivière",
  "Saint-Cyprien",
  "Saint-Cyr-au-Mont-d'Or",
  "Saint-Cyr-l'École",
  "Saint-Cyr-sur-Loire",
  "Saint-Cyr-sur-Mer",
  "Saint-Denis",
  "Saint-Denis-de-Pile",
  "Saint-Denis-en-Val",
  "Saint-Denis-lès-Bourg",
  "Saint-Didier-au-Mont-d'Or",
  "Saint-Dizier",
  "Saint-Dié-des-Vosges",
  "Saint-Doulchard",
  "Saint-Esprit",
  "Saint-Estève",
  "Saint-Fargeau-Ponthierry",
  "Saint-Florent-sur-Cher",
  "Saint-Flour",
  "Saint-Fons",
  "Saint-François",
  "Saint-Galmier",
  "Saint-Gaudens",
  "Saint-Genest-Lerpt",
  "Saint-Genis-Laval",
  "Saint-Genis-Pouilly",
  "Saint-Genis-les-Ollières",
  "Saint-Georges-d'Orques",
  "Saint-Georges-de-Didonne",
  "Saint-Germain-en-Laye",
  "Saint-Germain-lès-Arpajon",
  "Saint-Germain-lès-Corbeil",
  "Saint-Gervais-les-Bains",
  "Saint-Gilles",
  "Saint-Gilles-Croix-de-Vie",
  "Saint-Girons",
  "Saint-Gratien",
  "Saint-Grégoire",
  "Saint-Gély-du-Fesc",
  "Saint-Herblain",
  "Saint-Hilaire-de-Riez",
  "Saint-Hilaire-du-Harcouët",
  "Saint-Ismier",
  "Saint-Jacques-de-la-Lande",
  "Saint-James",
  "Saint-Jean",
  "Saint-Jean-Bonnefonds",
  "Saint-Jean-d'Angély",
  "Saint-Jean-d'Illac",
  "Saint-Jean-de-Boiseau",
  "Saint-Jean-de-Braye",
  "Saint-Jean-de-Luz",
  "Saint-Jean-de-Maurienne",
  "Saint-Jean-de-Monts",
  "Saint-Jean-de-Védas",
  "Saint-Jean-de-la-Ruelle",
  "Saint-Jean-le-Blanc",
  "Saint-Jorioz",
  "Saint-Jory",
  "Saint-Joseph",
  "Saint-Julien-de-Concelles",
  "Saint-Julien-en-Genevois",
  "Saint-Julien-les-Villas",
  "Saint-Junien",
  "Saint-Just-Saint-Rambert",
  "Saint-Just-en-Chaussée",
  "Saint-Juéry",
  "Saint-Laurent-Blangy",
  "Saint-Laurent-de-Mure",
  "Saint-Laurent-de-la-Salanque",
  "Saint-Laurent-du-Maroni",
  "Saint-Laurent-du-Var",
  "Saint-Leu",
  "Saint-Leu-la-Forêt",
  "Saint-Loubès",
  "Saint-Louis",
  "Saint-Lyphard",
  "Saint-Lys",
  "Saint-Lô",
  "Saint-Maixent-l'École",
  "Saint-Malo",
  "Saint-Mandrier-sur-Mer",
  "Saint-Mandé",
  "Saint-Marcel",
  "Saint-Marcel-lès-Valence",
  "Saint-Marcellin",
  "Saint-Marcellin-en-Forez",
  "Saint-Mars-du-Désert",
  "Saint-Martin",
  "Saint-Martin-Boulogne",
  "Saint-Martin-d'Hères",
  "Saint-Martin-d'Uriage",
  "Saint-Martin-de-Crau",
  "Saint-Martin-de-Seignanx",
  "Saint-Martin-la-Pallu",
  "Saint-Martin-le-Vinoux",
  "Saint-Martin-lez-Tatinghem",
  "Saint-Maur-des-Fossés",
  "Saint-Maurice",
  "Saint-Maurice-l'Exil",
  "Saint-Max",
  "Saint-Maximin-la-Sainte-Baume",
  "Saint-Memmie",
  "Saint-Michel-Chef-Chef",
  "Saint-Michel-sur-Orge",
  "Saint-Mitre-les-Remparts",
  "Saint-Médard-en-Jalles",
  "Saint-Nazaire",
  "Saint-Nicolas-de-Port",
  "Saint-Omer",
  "Saint-Orens-de-Gameville",
  "Saint-Ouen-l'Aumône",
  "Saint-Ouen-sur-Seine",
  "Saint-Pantaléon-de-Larche",
  "Saint-Pathus",
  "Saint-Paul",
  "Saint-Paul-Trois-Châteaux",
  "Saint-Paul-lès-Dax",
  "Saint-Philbert-de-Grand-Lieu",
  "Saint-Philippe",
  "Saint-Pierre",
  "Saint-Pierre-d'Irube",
  "Saint-Pierre-d'Oléron",
  "Saint-Pierre-des-Corps",
  "Saint-Pierre-du-Mont",
  "Saint-Pierre-du-Perray",
  "Saint-Pierre-en-Auge",
  "Saint-Pierre-en-Faucigny",
  "Saint-Pierre-lès-Elbeuf",
  "Saint-Pierre-lès-Nemours",
  "Saint-Pol-de-Léon",
  "Saint-Priest",
  "Saint-Priest-en-Jarez",
  "Saint-Privat-des-Vieux",
  "Saint-Prix",
  "Saint-Pryvé-Saint-Mesmin",
  "Saint-Pée-sur-Nivelle",
  "Saint-Péray",
  "Saint-Quentin",
  "Saint-Quentin-Fallavier",
  "Saint-Rambert-d'Albon",
  "Saint-Raphaël",
  "Saint-Renan",
  "Saint-Rémy",
  "Saint-Rémy-de-Provence",
  "Saint-Rémy-lès-Chevreuse",
  "Saint-Saturnin-lès-Avignon",
  "Saint-Saulve",
  "Saint-Sever",
  "Saint-Sulpice-la-Pointe",
  "Saint-Symphorien-d'Ozon",
  "Saint-Sébastien-de-Morsent",
  "Saint-Sébastien-sur-Loire",
  "Saint-Thibault-des-Vignes",
  "Saint-Vallier",
  "Saint-Victoret",
  "Saint-Vincent-de-Tyrosse",
  "Saint-Vit",
  "Saint-Xandre",
  "Saint-Yrieix-la-Perche",
  "Saint-Yrieix-sur-Charente",
  "Saint-Zacharie",
  "Saint-Égrève",
  "Saint-Étienne",
  "Saint-Étienne-au-Mont",
  "Saint-Étienne-de-Montluc",
  "Saint-Étienne-du-Rouvray",
  "Sainte-Adresse",
  "Sainte-Anne",
  "Sainte-Foy-lès-Lyon",
  "Sainte-Geneviève-des-Bois",
  "Sainte-Livrade-sur-Lot",
  "Sainte-Luce",
  "Sainte-Luce-sur-Loire",
  "Sainte-Marie",
  "Sainte-Maxime",
  "Sainte-Pazanne",
  "Sainte-Rose",
  "Sainte-Savine",
  "Sainte-Sigolène",
  "Sainte-Soulle",
  "Sainte-Suzanne",
  "Saintes",
  "Saintry-sur-Seine",
  "Salazie",
  "Saleilles",
  "Sallanches",
  "Sallaumines",
  "Salles",
  "Salon-de-Provence",
  "Sanary-sur-Mer",
  "Sannois",
  "Santes",
  "Saran",
  "Sarcelles",
  "Sarlat-la-Canéda",
  "Sarrebourg",
  "Sarreguemines",
  "Sarrians",
  "Sartrouville",
  "Sarzeau",
  "Sassenage",
  "Sathonay-Camp",
  "Saujon",
  "Saulx-les-Chartreux",
  "Saumur",
  "Sausheim",
  "Sausset-les-Pins",
  "Sautron",
  "Sauvian",
  "Savenay",
  "Saverne",
  "Savigny-le-Temple",
  "Savigny-sur-Orge",
  "Scaër",
  "Sceaux",
  "Schiltigheim",
  "Schweighouse-sur-Moder",
  "Schœlcher",
  "Sciez",
  "Scionzier",
  "Seclin",
  "Sedan",
  "Segré-en-Anjou Bleu",
  "Seichamps",
  "Seloncourt",
  "Senlis",
  "Sens",
  "Septèmes-les-Vallons",
  "Serris",
  "Servian",
  "Sevran",
  "Seysses",
  "Seyssinet-Pariset",
  "Seyssins",
  "Sigean",
  "Sillingy",
  "Simiane-Collongue",
  "Sin-le-Noble",
  "Sisteron",
  "Six-Fours-les-Plages",
  "Soissons",
  "Soisy-sous-Montmorency",
  "Soisy-sur-Seine",
  "Solliès-Pont",
  "Solliès-Toucas",
  "Somain",
  "Sommières",
  "Sorbiers",
  "Sorgues",
  "Sotteville-lès-Rouen",
  "Souffelweyersheim",
  "Souleuvre en Bocage",
  "Soultz-Haut-Rhin",
  "Soustons",
  "Soyaux",
  "Stains",
  "Stiring-Wendel",
  "Strasbourg",
  "Sucy-en-Brie",
  "Sucé-sur-Erdre",
  "Sully-sur-Loire",
  "Suresnes",
  "Surgères",
  "Sury-le-Comtal",
  "Surzur",
  "Sète",
  "Sèvremoine",
  "Sèvremont",
  "Sèvres",
  "Sélestat",
  "Séméac",
  "Sénas",
  "Séné",
  "Sérignan",
  "Tahaa",
  "Taiarapu-Est",
  "Taiarapu-Ouest",
  "Tain-l'Hermitage",
  "Talange",
  "Talant",
  "Talence",
  "Talmont-Saint-Hilaire",
  "Taputapuatea",
  "Tarare",
  "Tarascon",
  "Tarbes",
  "Tarnos",
  "Tassin-la-Demi-Lune",
  "Taverny",
  "Templeuve-en-Pévèle",
  "Tergnier",
  "Ternay",
  "Terrasson-Lavilledieu",
  "Terville",
  "Teva I Uta",
  "Thann",
  "Thaon-les-Vosges",
  "Theix-Noyalo",
  "Thiais",
  "Thiers",
  "Thionville",
  "Thizy-les-Bourgs",
  "Thoiry",
  "Thonon-les-Bains",
  "Thorigny-sur-Marne",
  "Thorigné-Fouillard",
  "Thouars",
  "Thouaré-sur-Loire",
  "Thue et Mue",
  "Thuir",
  "Thyez",
  "Thônes",
  "Tignieu-Jameyzieu",
  "Tinqueux",
  "Tomblaine",
  "Tonnay-Charente",
  "Tonneins",
  "Torcy",
  "Toul",
  "Toulon",
  "Toulouges",
  "Toulouse",
  "Tourcoing",
  "Tournan-en-Brie",
  "Tournefeuille",
  "Tournon-sur-Rhône",
  "Tournus",
  "Tours",
  "Tourves",
  "Trans-en-Provence",
  "Trappes",
  "Treillières",
  "Tremblay-en-France",
  "Tresses",
  "Trets",
  "Triel-sur-Seine",
  "Trignac",
  "Trilport",
  "Trith-Saint-Léger",
  "Trois-Rivières",
  "Troyes",
  "Trèbes",
  "Trégueux",
  "Trégunc",
  "Trélazé",
  "Trélissac",
  "Trévoux",
  "Tsingoni",
  "Tulle",
  "Tullins",
  "Téteghem-Coudekerque-Village",
  "Uckange",
  "Ugine",
  "Unieux",
  "Urrugne",
  "Ussel",
  "Ustaritz",
  "Uvea",
  "Uzès",
  "Vaires-sur-Marne",
  "Vaison-la-Romaine",
  "Val de Briey",
  "Val-de-Moder",
  "Val-de-Reuil",
  "Valbonne",
  "Valdahon",
  "Valdallière",
  "Valdoie",
  "Valence",
  "Valenciennes",
  "Valentigney",
  "Valenton",
  "Vallauris",
  "Valleiry",
  "Vallet",
  "Vallons-de-l'Erdre",
  "Valognes",
  "Valréas",
  "Valserhône",
  "Vandœuvre-lès-Nancy",
  "Vannes",
  "Vanves",
  "Varces-Allières-et-Risset",
  "Varennes-Vauzelles",
  "Vaucresson",
  "Vaugneray",
  "Vaujours",
  "Vaulx-en-Velin",
  "Vauréal",
  "Vauvert",
  "Vaux-le-Pénil",
  "Vaux-sur-Seine",
  "Veauche",
  "Vedène",
  "Veigné",
  "Velaux",
  "Vence",
  "Vendargues",
  "Vendenheim",
  "Vendin-le-Vieil",
  "Vendôme",
  "Venelles",
  "Ventabren",
  "Verdun",
  "Vergèze",
  "Vern-sur-Seiche",
  "Vernaison",
  "Verneuil d'Avre et d'Iton",
  "Verneuil-sur-Seine",
  "Vernon",
  "Vernouillet",
  "Verrières-en-Anjou",
  "Verrières-le-Buisson",
  "Versailles",
  "Vert-Saint-Denis",
  "Vertou",
  "Vesoul",
  "Vexin-sur-Epte",
  "Vezin-le-Coquet",
  "Viarmes",
  "Vias",
  "Vic-le-Comte",
  "Vichy",
  "Vidauban",
  "Vienne",
  "Vierzon",
  "Vieux-Condé",
  "Vieux-Habitants",
  "Vif",
  "Vigneux-de-Bretagne",
  "Vigneux-sur-Seine",
  "Villabé",
  "Villard-Bonnot",
  "Villars",
  "Villars-les-Dombes",
  "Ville-d'Avray",
  "Ville-la-Grand",
  "Villebon-sur-Yvette",
  "Villecresnes",
  "Villefontaine",
  "Villefranche-de-Lauragais",
  "Villefranche-de-Rouergue",
  "Villefranche-sur-Mer",
  "Villefranche-sur-Saône",
  "Villejuif",
  "Villemandeur",
  "Villemoisson-sur-Orge",
  "Villemomble",
  "Villemur-sur-Tarn",
  "Villenave-d'Ornon",
  "Villeneuve-Loubet",
  "Villeneuve-Saint-Georges",
  "Villeneuve-Tolosane",
  "Villeneuve-d'Ascq",
  "Villeneuve-en-Retz",
  "Villeneuve-la-Garenne",
  "Villeneuve-le-Roi",
  "Villeneuve-lès-Avignon",
  "Villeneuve-lès-Maguelone",
  "Villeneuve-sur-Lot",
  "Villeneuve-sur-Yonne",
  "Villennes-sur-Seine",
  "Villenoy",
  "Villeparisis",
  "Villepinte",
  "Villepreux",
  "Villerest",
  "Villers-Cotterêts",
  "Villers-Saint-Paul",
  "Villers-le-Lac",
  "Villers-lès-Nancy",
  "Villerupt",
  "Villetaneuse",
  "Villette-d'Anthon",
  "Villeurbanne",
  "Villiers-le-Bel",
  "Villiers-sur-Marne",
  "Vincennes",
  "Vindry-sur-Turdine",
  "Vineuil",
  "Vire Normandie",
  "Viriat",
  "Viroflay",
  "Viry",
  "Viry-Châtillon",
  "Vitrolles",
  "Vitry-le-François",
  "Vitry-sur-Seine",
  "Vitré",
  "Vizille",
  "Voiron",
  "Voisins-le-Bretonneux",
  "Voreppe",
  "Vouneuil-sous-Biard",
  "Vélizy-Villacoublay",
  "Vénissieux",
  "Vétraz-Monthoux",
  "Wallers",
  "Wambrechies",
  "Wasquehal",
  "Wasselonne",
  "Wattignies",
  "Wattrelos",
  "Wavrin",
  "Waziers",
  "Wervicq-Sud",
  "Wimereux",
  "Wingles",
  "Wintzenheim",
  "Wissembourg",
  "Wissous",
  "Wittelsheim",
  "Wittenheim",
  "Woippy",
  "Wormhout",
  "Yerres",
  "Yffiniac",
  "Yssingeaux",
  "Yutz",
  "Yvetot",
  "Yzeure",
  "Échirolles",
  "Écouen",
  "Écully",
  "Égly",
  "Éguilles",
  "Élancourt",
  "Émerainville",
  "Épernay",
  "Épernon",
  "Épinal",
  "Épinay-sous-Sénart",
  "Épinay-sur-Orge",
  "Épinay-sur-Seine",
  "Épône",
  "Éragny-sur-Oise",
  "Étampes",
  "Étaples",
  "Étoile-sur-Rhône",
  "Étréchy",
  "Évian-les-Bains",
  "Évreux",
  "Évron",
  "Évry-Courcouronnes",
  "Ézanville",
];
export const LANGUAGES = ["Français", "Arabe", "Bilingue", "Anglais"];
